### PR TITLE
feat: setup installation URL override

### PR DESCRIPTION
**Pull request by ryan-timothy-albert**

### CODE REVIEW

**Comment by chendrix** [comment]
does the gen.lock not get auto-updated with the gen.yaml not having `installationURL` ?

**Comment by chendrix** [comment]
I ran the run locally and it worked, but my understanding of a `.yaml` / `.lock` file system is you only ever update the `.yaml` and the `.lock` is auto-generated & meant to stay static.

**Comment by ryan-timothy-albert** [comment]
> I ran the run locally and it worked, but my understanding of a `.yaml` / `.lock` file system is you only ever update the `.yaml` and the `.lock` is auto-generated & meant to stay static.

It is intended to be static, I think we missed something specifically with installationURL configuration, the value should have been moved over. I would still set this value for now because it will stay configured as intended, but we will make it so you don't have to manually set it in the future.

**Comment by ryan-timothy-albert** [comment]
> does the gen.lock not get auto-updated with the gen.yaml not having `installationURL` ?

It does not. They do not update one anothers values. I do agree it makes sense if you have a value under gen.yaml that's meant to be under gen.lock we just move it over for you automatically so you don't ever need to edit gen.lock, I'll look into this.

**Review by chendrix — APPROVED** [review]

**Pull request merged**
